//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game_Genre
    {
        public int ID_Game_Genre { get; set; }
        public int ID_Game { get; set; }
        public int ID_Genre { get; set; }
    
        public virtual Games Games { get; set; }
        public virtual Genres Genres { get; set; }
    }
}
