//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logging3
    {
        public int id_log3 { get; set; }
        public int id_okna3 { get; set; }
        public string name_talon3 { get; set; }
        public string time { get; set; }
        public string rabota_s_klientom { get; set; }
    }
}
