//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logging2
    {
        public int id_log2 { get; set; }
        public int id_okna2 { get; set; }
        public string name_talon2 { get; set; }
        public System.DateTime datatame2 { get; set; }
        public Nullable<System.DateTime> date_raznica { get; set; }
    }
}
