//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_TalonsEntities1 : DbContext
    {
        public db_TalonsEntities1()
            : base("name=db_TalonsEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Logging> Logging { get; set; }
        public virtual DbSet<Logging2> Logging2 { get; set; }
        public virtual DbSet<Logging3> Logging3 { get; set; }
        public virtual DbSet<Talons> Talons { get; set; }
        public virtual DbSet<WindowStatus> WindowStatus { get; set; }
    }
}
