//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersBD
    {
        public int ID_User { get; set; }
        public string First_Name { get; set; }
        public string Second_Name { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public bool Administrator { get; set; }
    }
}
