//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowChrome.Demo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_MinligareevMAContext : DbContext
    {
        public db_MinligareevMAContext()
            : base("name=db_MinligareevMAContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<Developers> Developers { get; set; }
        public virtual DbSet<Exhibitions> Exhibitions { get; set; }
        public virtual DbSet<Game_Area> Game_Area { get; set; }
        public virtual DbSet<Game_Exhibition> Game_Exhibition { get; set; }
        public virtual DbSet<Game_Genre> Game_Genre { get; set; }
        public virtual DbSet<Games> Games { get; set; }
        public virtual DbSet<Genres> Genres { get; set; }
        public virtual DbSet<Publishers> Publishers { get; set; }
        public virtual DbSet<errors> errors { get; set; }
    }
}
