//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowChrome.Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game_Exhibition
    {
        public int ID_Game_Exhibition { get; set; }
        public int ID_Game { get; set; }
        public int ID_Exhibition { get; set; }
        public double Game_Rating_On_Exhibition { get; set; }
    
        public virtual Exhibitions Exhibitions { get; set; }
        public virtual Games Games { get; set; }
    }
}
